### ISSUE TITLE
签名验签不正确

### ISSUE THREAD

**Issue by hpy777** [songgeng87/SM9_FREE#1]
cks:="\x86\xDC\xD6\x4F\xEB\x81\xA7\x19\x63\x59\x59\xF1\xA5\xC2\xF9\x88\xBD\x39\x43\x1B\x08\xA8\x63\xF0\x42\x8D\x21\xDF\xFA\xF2\xBF\x89"
id:="\x41\x6C\x69\x63\x65"
msg := "\x43\x68\x69\x6E\x65\x73\x65\x20\x49\x42\x53\x20\x73\x74\x61\x6E\x64\x61\x72\x64"
rand:="\x1A\x23\x29\x77\xBA\x9F\xA2\xD1\xC5\x58\xF2\xD4\x67\xFE\x7B\xE7\x04\x05\x41\x26\x73\xF8\xBE\x64\x9B\xBD\xD4\xA0\x95\xBE\x1B\x4B"

---------------------------------------结果----xs显示不全-------------------------------------
h：  396fb96c805e65426b1120c27edf86ecc1e36f88e8fdd1f59cbfc573c20536b0
xs：  52a37a7ab0b9016147593d068370268dd6e011e8443fffc194
ys：  2eaaba9d337a3cbc8562e1e22794f69f950b82785fe2df7e512ec9588ae3cfa8

**Comment by songgeng87** [comment]
能提供下编译环境么？

**Comment by hpy777** [comment]
我用的makefile编译的

**Comment by hpy777** [comment]
邮箱发给你了哈

**Comment by songgeng87** [comment]
0x39,0x6f,0xb9,0x6c,0x80,0x5e,0x65,0x42,0x6b,0x11,0x20,0xc2,0x7e,0xdf,0x86,0xec,
0xc1,0xe3,0x6f,0x88,0xe8,0xfd,0xd1,0xf5,0x9c,0xbf,0xc5,0x73,0xc2,0x05,0x36,0xb0,
==================
0x52,0xa3,0x7a,0x7a,0xb0,0xb9,0x01,0x61,0x47,0x59,0x3d,0x06,0x83,0x70,0x26,0x8d,
0xd6,0xe0,0x11,0xe8,0x44,0x3f,0xff,0xc1,0x94,0x00,0x95,0x15,0x46,0xe7,0xdd,0x9c,
==================
0x2e,0xaa,0xba,0x9d,0x33,0x7a,0x3c,0xbc,0x85,0x62,0xe1,0xe2,0x27,0x94,0xf6,0x9f,
0x95,0x0b,0x82,0x78,0x5f,0xe2,0xdf,0x7e,0x51,0x2e,0xc9,0x58,0x8a,0xe3,0xcf,0xa8,

我使用你的makefile编译成功，再使用你提供的参数，跑出来的结果是这个，可以验证完成。

看看是否你对xs有过其他操作？

**Comment by hpy777** [comment]
你这个结果是对的，我也不是很清楚为什么经常出现签名不完整的问题，我是用go调用了你这个c库
