### ISSUE TITLE
SM9_Init

### ISSUE THREAD

**Issue by sz777** [songgeng87/SM9_FREE#3]
SM9_Init函数始终返回1 ，建议初始化成功返回其他值

**Comment by songgeng87** [comment]
多谢检查，我已发现问题所在，近日更新。

**Comment by songgeng87** [comment]
请给项目star

**Comment by songgeng87** [comment]
错误返回码已经更新，具体可查看sm9_algorithm.h

**Comment by sz777** [comment]
你好：关于我的一些理解，sm9签名部分秘钥分为四类


1、用户私钥（一串随机数）
2、用户公钥（id）

3、系统私钥（由 系统公钥+id 生成）
4、系统公钥(由 用户私钥 生成)


不知道我上述的理解是否正确，如有错误的地方请指正


疑问点：签名通过系统私钥，验签为什么不通过系统公钥，而是通过用户公钥验证呢？


for(int i=0;i<TEST;i++){// 验证函数
        res = SM9_Verify(msg, 20, &sign, &pk, NULL);
        if (res) printf("verify error at %d = %d\n", i,res);
    }

**Comment by sz777** [comment]
我看文档上这么写的

func sign (系统参数、签名主公钥Ppub-s、消息M和签名密钥 dsA){}

func verify(系统参数、签名主公钥 Ppub-s、识别符 hid、标识 IDA、消息 M’及其数字签名(h’, S’)){}



虽然在 SM9_FREE里 签名、验签方法参数都未传入 “签名主公钥Ppub-s” 这个参数
但我看到了 在“签名方法”中在内部对该参数“签名主公钥Ppub-s”进行了生成 


然而“验签方法”中好像未提及该参数“签名主公钥Ppub-s”

**Comment by sz777** [comment]
/** 
	* 签名
	* 
	* @param masterPublicKey 签名主公钥
	* @param prikey 用户签名私钥
	* @param data 待签数据
	* @return 签名值
	*/
--------------------- 








/**
	* 验签
	*
	* @param masterPublicKey 签名主公钥
	* @param prikey 用户ID
	* @param signature 签名值
	* @param data 待签数据
	* @return true-验签成功；false-验签失败
	*/
--------------------- 




我的理解是这样子
但是在验签部分为看到出现 “签名主公钥” 不知道是封装在哪里了

**Comment by songgeng87** [comment]
在代码中，签名主公钥被init函数作为系统参数做全局存储了。

**Comment by sz777** [comment]
感谢




------------------ 原始邮件 ------------------
发件人: "宋赓"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 下午2:39
收件人: "songgeng87/SM9_FREE"<SM9_FREE@noreply.github.com>;
抄送: "黛月如歌"<1011094143@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [songgeng87/SM9_FREE] SM9_Init (#3)




在代码中，签名主公钥被init函数作为系统参数做全局存储了。

**Comment by songgeng87** [comment]
应该是在 SM9_Set_Sign 函数内设置的。

类似的还有SM9_Set_Encrypt，SM9_Set_KeyExchange。

具体使用可以参考sm9_algorithm.h头文件

**Comment by sz777** [comment]
收到，我研究一下




------------------ 原始邮件 ------------------
发件人: "宋赓"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 下午2:43
收件人: "songgeng87/SM9_FREE"<SM9_FREE@noreply.github.com>;
抄送: "黛月如歌"<1011094143@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [songgeng87/SM9_FREE] SM9_Init (#3)




应该是在 SM9_Set_Sign 函数内设置的。
 
类似的还有SM9_Set_Encrypt，SM9_Set_KeyExchange。
 
具体使用可以参考sm9_algorithm.h头文件

**Comment by sz777** [comment]
博主，你好，我如果只拿到了如下值我应该如何做验签呢，能否给我一些思路
/**
	* 验签
	*
	* @param masterPublicKey 签名主公钥
	* @param prikey 用户ID
	* @param signature 签名值
	* @param data 待签数据
	* @return true-验签成功；false-验签失败
	*/



系统主秘钥：
x1: 745992262F016C3A25C6689ABD1ECB9D5A8DC05D46328E80ADE687D8049272F0
x2: B05C0B059E72237C28F805E41A8DE7734DD8055BDBCA5025761E64E408548B7E
y1: 4158879766A662C17C7E5BB46CF4FFF9700A0A75B42CE39C699455D3C8F34951
y2: 6A147DEA66D24F6F8B609D473E6E7B84301AECF4794C7AE88207697F01F509D4


用户ID：Alice 


签名原文：Chinese IBS standard


签名值
h: 2D07F4F52DA42B79FDF7A94B85FE45EB2898DEDF43D34D57D3CFD34979E5F1F8
xs: 8AF689474407EEDB4AC7619981604E33EE47873B39E66C60DDDA5B8E70B046E7
ys: A7873CFAE73AC0250A35432BC6EB369029466574540F2036EB66C5CEF5B93A09

**Comment by songgeng87** [comment]
你这个主秘钥是公钥吧？
启动一下签名lib
SM9_Set_Sign(mspk.x1, mspk.x2, mspk.y1, mspk.x2, NULL);
就可以调用
SM9_Verify(msg, 20, &sign, &pk, NULL); 
完成验签了

**Comment by sz777** [comment]
是的 系统主公钥，我刚刚也是这么操作的 但是验签失败 不知道是否是我哪里操作不对




------------------ 原始邮件 ------------------
发件人: "宋赓"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 下午3:38
收件人: "songgeng87/SM9_FREE"<SM9_FREE@noreply.github.com>;
抄送: "黛月如歌"<1011094143@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [songgeng87/SM9_FREE] SM9_Init (#3)




你这个主秘钥是公钥吧？
 启动一下签名lib
 SM9_Set_Sign(mspk.x1, mspk.x2, mspk.y1, mspk.x2, NULL);
 就可以调用
 SM9_Verify(msg, 20, &sign, &pk, NULL);
 完成验签了

**Comment by sz777** [comment]
博主你好，我已反复试验多次，还是不行，不知是否是其他问题


SM9_Init(0,0,32,NULL,NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );



gg = SM9_Set_Sign(mspk.x1, mspk.x2, mspk.y1, mspk.x2, NULL); // 启动签名lib
    
SM9_Set_Sign(NULL, NULL, NULL, NULL, gg);



SM9_Verify(msg, 20, &sign, &pk, NULL);

**Comment by songgeng87** [comment]
我更新了代码，修复了一个BUG。

关于验证，可以参考SM9Test.c中的”独立验证“部分。

单独运行该部分也是能够正确验证的。

顺序
SM9_Init(0,0,32,NULL,NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
gg = SM9_Set_Sign(mspk.x1, mspk.x2, mspk.y1, mspk.y2, NULL); // 启动签名lib
SM9_Verify(msg, 20, &sign, &pk, NULL);

我使用自己随机生成的签名能通过验证。但是你的数据无法正确通过验证。

**Comment by sz777** [comment]
好的 我晚上试一下 我那组数据么是用exe工具生成出来的

**Comment by sz777** [comment]
你好博主，SM9Test.C文件可编译，但无法执行，是可执行文件中有字符不识别好像

**Comment by sz777** [comment]
我跟新了版本，用go语言调用时 提示这句报错：SM9_Set_Sign(NULL, NULL, NULL, NULL, gg);

但是之前版本没问题

**Comment by sz777** [comment]
SM9_Init(0,0,32,NULL,NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
gg = SM9_Set_Sign(mspk.x1, mspk.x2, mspk.y1, mspk.2, NULL); // 启动签名lib
SM9_Set_Sign(NULL, NULL, NULL, NULL, gg);  //如果将SM9Test.c 80行这句注释掉，那么可以正常显示结果
SM9_Verify(msg, 20, &sign, &pk, NULL);

**Comment by sz777** [comment]
SM9_Init(0,0,32,NULL,NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
gg = SM9_Set_Sign(mspk.x1, mspk.x2, mspk.y1, mspk.2, NULL); // 启动签名lib
SM9_Set_Sign(NULL, NULL, NULL, NULL, gg);  //如果将SM9Test.c 80行这句注释掉，那么可以运行，但是结果不正常
SM9_Verify(msg, 20, &sign, &pk, NULL);

**Comment by songgeng87** [comment]
原先的SM9Test.c 里面gg = SM9_Set_Sign(mspk.x1, mspk.x2, mspk.y1, mspk.2, NULL); 传入参数有误，应该分别传入mspk的 x1 x2 y1 y2 ，请仔细检查
请参考我最新的SM9Test.c
SM9_Set_Sign(NULL, NULL, NULL, NULL, gg)函数需要要求gg返回不是NULL才能继续执行。

**Comment by sz777** [comment]
感谢，刚刚注意到这个细节




------------------ 原始邮件 ------------------
发件人: "宋赓"<notifications@github.com>;
发送时间: 2019年5月16日(星期四) 中午11:02
收件人: "songgeng87/SM9_FREE"<SM9_FREE@noreply.github.com>;
抄送: "黛月如歌"<1011094143@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [songgeng87/SM9_FREE] SM9_Init (#3)




原先的SM9Test.c 里面gg = SM9_Set_Sign(mspk.x1, mspk.x2, mspk.y1, mspk.2, NULL); 传入参数有误，应该分别传入mspk的 x1 x2 y1 y2 ，请仔细检查
 请参考我最新的SM9Test.c
 SM9_Set_Sign(NULL, NULL, NULL, NULL, gg)函数需要要求gg返回不是NULL才能继续执行。

**Comment by songgeng87** [comment]
有问题再继续交流~

**Comment by sz777** [comment]
博主你好，不知道为什么我如果原文msg任意换成其他东西，总是验签失败
比如msg="abc"

**Comment by sz777** [comment]
主公钥：7BAF4793ED3B88B86DBA318928D9ABCFFA4EA692805BBCC72CF694B754A2A644
6BE0FCC25FB77D0B3AA3DA70A715B765E96362633CC53CB5F7C7687CF2FE0547
144E943A529A161B8323433A437CD9C2DA72C29A31EC557FCDF489BE54045A30
93E858BBB7DB7AAE54050E82CE78EF86652B5626BF3AE72997CB6714DE5AE655

原文：
616263


签名结果h:
8D600AFA46D9B8D334B604F61BC8EC21328230D28CB234AD3F1FDA5B729A5455
签名结果s:
53AC5478C3B5F524F682A28E6FE40F9CC6914939721B5F1B46FB8EBDE537F2C4
B0A633D03BD90BFF72F31E0A84DD4F2234AA9276783CD759CA2F89517B455688

**Comment by sz777** [comment]
不知道为什么 msg = "Chinese IBS standard" 签名结果正确
msg为其他，签名结果与验算工具结果不一致

**Comment by sz777** [comment]
调用签名函数时，即使传入同一组参数（cks,id,rand），每次执行签名，结果好像也会不同

**Comment by sz777** [comment]
在吗？博主

**Comment by sz777** [comment]
好的博主，刚刚看到你的消息，麻烦了

**Comment by sz777** [comment]
你好博主，sm9代码


发现一个bug, id=mqq , 签名原文=mqqq的时候，签名结果和测试工具的结果不太一样

**Comment by sz777** [comment]
你好博主，sm9发现一个bug, id=mqq , 签名原文=mqqq的时候，签名结果和测试工具的结果不太一样

**Comment by sz777** [comment]
盼复

**Comment by sz777** [comment]
感谢，问题已经解决，是我的问题
