### ISSUE TITLE
加解密问题

### ISSUE THREAD

**Issue by hpy777** [songgeng87/SM9_FREE#4]
--------------------------加密测试参数--------------------------
unsigned char cmsg[20] = {"\x43\x68\x69\x6E\x65\x73\x65\x20\x49\x42\x45\x20\x73\x74\x61\x6E\x64\x61\x72\x64"};
    unsigned char eks[32] = {"\x00\x01\xED\xEE\x37\x78\xF4\x41\xF8\xDE\xA3\xD9\xFA\x0A\xCC\x4E\x07\xEE\x36\xC9\x3F\x9A\x08\x61\x8A\xF4\xAD\x85\xCE\xDE\x1C\x22"};
    unsigned char eid[3] = {"\x42\x6F\x62"};
    unsigned char er[32] = {"\x00\x00\xAA\xC0\x54\x17\x79\xC8\xFC\x45\xE3\xE2\xCB\x25\xC1\x2B\x5D\x25\x76\xB2\x12\x9A\xE8\xBB\x5E\xE2\xCB\xE5\xEC\x9E\x78\x5C"};

注：这个加密结果前半部分 x+y都是一致的，后半部分是c3+cp吗 好像不太一样

--------------------------调用库得到的结果--------------------------
x： 2445471164490618e1ee20528ff1d545b0f14c8bcaa44544f03dab5dac07d8ff
y： 42ffca97d57cddc05ea405f2e586feb3a6930715532b8000759f13059ed59ac0
c3： fd3c98dd92c44c68332675a370cceede31e0c5cd209c257601149d12b394a2be
cp： e05b6fac6f11b965268c994f00dba7a8bb00fd60583546cbdf4649250863f10a

--------------------------测试工具得到的结果--------------------------
2445471164490618E1EE20528FF1D545B0F14C8BCAA44544F03DAB5DAC07D8FF42FFCA97D57CDDC05EA405F2E586FEB3A6930715532B8000759F13059ED59AC0DEA278E55F9ECB2ECD98E4BA8C8B8EF05571D2AFB3BD94BA8563E236125055A163451E20CD57DFB0722D6D0C8731573FBB00FD60583546CBDF4649250863F10A

**Comment by songgeng87** [comment]
经查，该项目输出的结果与标准中提供的参考数据一致，没有错误。
请查看https://github.com/songgeng87/SM9_FREE/blob/master/SM9_FREE/SM9%E6%96%87%E6%A1%A3/SM9_5.pdf 第23页。

请给项目star~~

**Comment by hpy777** [comment]
好的 ，我再看一下

**Comment by sz777** [comment]
结果确实一致

**Comment by hpy777** [comment]
结果确实一致

**Comment by hpy777** [comment]
是我原文写错了，签名原文Chinese IBS standard，加密原文Chinese IBE standard
