### ISSUE TITLE
关于生成签名公钥的问题

### ISSUE THREAD

**Issue by hpy777** [songgeng87/SM9_FREE#5]
SM9_PK pk = SM9_PK_New(5, id);       // 申明一个签名公钥，不知签名公钥是否根据id生成

标准文档https://github.com/songgeng87/SM9_FREE/blob/master/SM9_FREE/SM9%E6%96%87%E6%A1%A3/SM9_2.pdf数字签名算法部分第2页1.4：签名主公钥由签名主私钥结合系统参数产生

**Comment by songgeng87** [comment]
主公钥是由私钥产生的。
普通用户的公钥就是其ID

**Comment by hpy777** [comment]
/**
	* 验签
	*
	* @param masterPublicKey 签名主公钥
	* @param prikey 用户ID
	* @param signature 签名值
	* @param data 待签数据
	* @return true-验签成功；false-验签失败
	*/
---------------------


我的理解是这样子
但是在验签部分未看到出现 “签名主公钥” 不知道是封装在哪里了，能否给我一些提示
