### ISSUE TITLE
宋老师，您好。Makefile有问题，在gcc下面无法编译

### ISSUE THREAD

**Issue by boboIqiqi** [songgeng87/SM9_FREE#8]
@songgeng87 宋老师，您好。
我直接按照说明，运行
```
make test
```
提示如下：
<img width="845" alt="songgeng87_make_test" src="https://user-images.githubusercontent.com/1284515/79294043-cb44be00-7f07-11ea-9688-f6e958431a83.png">

**Comment by songgeng87** [comment]
我这边看起来一切正常。

**Comment by boboIqiqi** [comment]
我按照 #7  issue7中的修改，现在可以了。感谢回复。

**Comment by Chenxianshang** [comment]
同学请问下问题是怎么解决的？issue7中增加c99编译不是已经实现了么，请问您是怎么修改的？
